/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#1c1b1b",
        "on-surface-variant": "#444748",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#ddd9d5",
        "surface-container-high": "#ebe8e3",
        "error": "#ba1a1a",
        "on-secondary-container": "#745c00",
        "secondary": "#735c00",
        "surface-container-low": "#f7f3ee",
        "surface": "#fdf9f4",
        "tertiary-fixed-dim": "#bfcd8f",
        "surface-variant": "#e6e2dd",
        "on-primary-container": "#858383",
        "on-secondary-fixed": "#241a00",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1c1c19",
        "surface-container-highest": "#e6e2dd",
        "surface-bright": "#fdf9f4",
        "secondary-fixed": "#ffe088",
        "inverse-surface": "#31302d",
        "tertiary-fixed": "#dbe9a9",
        "on-error-container": "#93000a",
        "background": "#fdf9f4",
        "surface-container": "#f1ede8",
        "primary-fixed": "#e5e2e1",
        "primary-container": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
        "on-tertiary-fixed": "#171e00",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-container": "#fed65b",
        "on-secondary-fixed-variant": "#574500",
        "primary": "#000000",
        "secondary-fixed-dim": "#e9c349",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#7d8952",
        "inverse-on-surface": "#f4f0eb",
        "tertiary-container": "#171e00",
        "inverse-primary": "#c8c6c5",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#404b1b",
        "tertiary": "#000000",
        "on-surface": "#1c1c19",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "section-gap": "120px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "unit": "8px",
        "container-max": "1280px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "headline-md": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
