/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#1c1b1b",
        "on-surface-variant": "#444748",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#ddd9d5",
        "surface-container-high": "#ebe8e3",
        "error": "#ba1a1a",
        "on-secondary-container": "#745c00",
        "secondary": "#735c00",
        "surface-container-low": "#f7f3ee",
        "surface": "#fdf9f4",
        "tertiary-fixed-dim": "#bfcd8f",
        "surface-variant": "#e6e2dd",
        "on-primary-container": "#858383",
        "on-secondary-fixed": "#241a00",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-background": "#1c1c19",
        "surface-container-highest": "#e6e2dd",
        "surface-bright": "#fdf9f4",
        "secondary-fixed": "#ffe088",
        "inverse-surface": "#31302d",
        "tertiary-fixed": "#dbe9a9",
        "on-error-container": "#93000a",
        "background": "#fdf9f4",
        "surface-container": "#f1ede8",
        "primary-fixed": "#e5e2e1",
        "primary-container": "#1c1b1b",
        "on-primary-fixed-variant": "#474746",
        "on-tertiary-fixed": "#171e00",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-container": "#fed65b",
        "on-secondary-fixed-variant": "#574500",
        "primary": "#000000",
        "secondary-fixed-dim": "#e9c349",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#7d8952",
        "inverse-on-surface": "#f4f0eb",
        "tertiary-container": "#171e00",
        "inverse-primary": "#c8c6c5",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#404b1b",
        "tertiary": "#000000",
        "on-surface": "#1c1c19",
        "outline": "#747878",
        "outline-variant": "#c4c7c7",
        "surface-tint": "#5f5e5e",

        // Admin Design System Colors
        "admin-primary": "#001736",
        "admin-on-primary": "#ffffff",
        "admin-primary-container": "#002b5b",
        "admin-on-primary-container": "#7594ca",
        "admin-secondary": "#115cb9",
        "admin-on-secondary": "#ffffff",
        "admin-secondary-container": "#659dfe",
        "admin-on-secondary-container": "#003370",
        "admin-tertiary": "#2f0c00",
        "admin-on-tertiary": "#ffffff",
        "admin-tertiary-container": "#4f1c02",
        "admin-on-tertiary-container": "#cd805d",
        "admin-background": "#f8f9ff",
        "admin-on-background": "#0b1c30",
        "admin-surface": "#f8f9ff",
        "admin-on-surface": "#0b1c30",
        "admin-surface-variant": "#d3e4fe",
        "admin-on-surface-variant": "#43474f",
        "admin-outline": "#747780",
        "admin-outline-variant": "#c4c6d0",
        "admin-surface-container-lowest": "#ffffff",
        "admin-surface-container-low": "#eff4ff",
        "admin-surface-container": "#e5eeff",
        "admin-surface-container-high": "#dce9ff",
        "admin-surface-container-highest": "#d3e4fe",
        "admin-surface-dim": "#cbdbf5",
        "admin-surface-bright": "#f8f9ff",
        "admin-primary-fixed": "#d6e3ff",
        "admin-primary-fixed-dim": "#a9c7ff",
        "admin-on-primary-fixed": "#001b3d",
        "admin-on-primary-fixed-variant": "#264778",
        "admin-secondary-fixed": "#d7e2ff",
        "admin-secondary-fixed-dim": "#acc7ff",
        "admin-on-secondary-fixed": "#001a40",
        "admin-on-secondary-fixed-variant": "#004491",
        "admin-tertiary-fixed": "#ffdbcd",
        "admin-tertiary-fixed-dim": "#ffb596",
        "admin-on-tertiary-fixed": "#360f00",
        "admin-on-tertiary-fixed-variant": "#713619",
        "admin-surface-tint": "#405f91",
        "admin-inverse-surface": "#213145",
        "admin-inverse-on-surface": "#eaf1ff",
        "admin-inverse-primary": "#a9c7ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "section-gap": "120px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "unit": "8px",
        "container-max": "1280px",
        "margin-mobile": "20px",

        // Admin Spacing Extensions
        "admin-sidebar-width": "260px",
        "admin-lg": "24px",
        "admin-md": "16px",
        "admin-base": "4px",
        "admin-container-max": "1440px",
        "admin-xs": "4px",
        "admin-xl": "32px",
        "admin-sm": "8px"
      },
      fontFamily: {
        "headline-md": ["EB Garamond", "serif"],
        "display-lg": ["EB Garamond", "serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg-mobile": ["EB Garamond", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["EB Garamond", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],

        // Admin Font Extensions
        "admin-sans": ["Inter", "sans-serif"],
        "admin-mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "400" }],

        // Admin FontSize Extensions
        "admin-display-lg": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "admin-headline-md": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "admin-headline-sm": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "admin-body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "admin-body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "admin-body-sm": ["13px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "admin-label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "admin-data-mono": ["14px", { "lineHeight": "1.4", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
